- name: "KUBERNETES - ADDING KUBERNETES GPG KEY"
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: "present"
  register: "add_repository_key"
  ignore_errors: true

- name: "KUBERNETES - REQUIRED CONFIG"
  shell:
    cmd: |
      cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
      deb http://apt.kubernetes.io/ kubernetes-xenial main
      EOF
  args:
    executable: /bin/zsh

- name: "KUBERNETES - REQUIRED PACKAGES INSTALLATION"
  package:
    name:
      - "kubelet"
      - "kubeadm"
      - "kubectl"
    state: "present"
    update_cache: "yes"

- name: "KUBERNETES - HOLD MARK TO AVOID UPGRADES"
  shell: apt-mark hold kubelet kubeadm kubectl

- name: "KUBERNETES - KUBELET REQUIRES SWAP OFF"
  shell: swapoff -a

- name: "KUBERNETES - KEEP SWAP OFF AFTER REBOOT"
  shell: sed -i '/ swap / s/^/#/' /etc/fstab
  args:
    warn: false
