---
- hosts: ubuntu3
  become: true
  tasks:
    - name: "install PostgreSQL"
      apt:
        name:
          - postgresql
          - postgresql-contrib
          - libpq-dev
          - python-psycopg2
        state: present
        update_cache: yes

    - name: Ensure the Postgres service is running
      service:
        name: postgresql
        state: started
        enabled: yes
